<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows7.0</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<!-- Cấu hình đóng gói: xuất ra 1 file .exe duy nhất, tự cung cấp .NET, chạy trên mọi máy Win10/11 x64 -->
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>

		<!-- Nén file giúp giảm dung lượng .EXE -->
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>

		<!-- Windows Forms không tương thích tốt với Full Trim, giữ false nhưng loại bỏ symbol -->
		<PublishTrimmed>false</PublishTrimmed>
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
		<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
		<ApplicationIcon>m_logo_icon_167921.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
	  <Content Include="m_logo_icon_167921.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2535.41" />
	</ItemGroup>
</Project>